### ISSUE TITLE
Fix tracking of bundles assigned to a pool

### ISSUE THREAD

**Issue by doerfli** [etherisc/gif-next#173]
https://github.com/etherisc/gif-next/blob/develop/contracts/instance/service/PoolService.sol#L136 

- [x] Track the active and complete list of bundle that are in the pool. 
- [ ] Track active and complete list risks that exist for a product  (`RiskManager` ... similar to `BundleManager`)
- [ ] Track which policies are assigned to which risk

**Comment by matthiaszimmermann** [comment]
similar topics to be considered in the same context:
- active and total set of policies per product
- set of active policies covered by a specific bundle

**Comment by matthiaszimmermann** [comment]
sketch: additional helper contracts:
- BundleManager: manages bundles per pool, and policies per bundle
- PolicyManager: manages policies per product, and policies per risk
- DistributionManager: manages distributors per distribution, and referrals per distributor
- OracleManager: manages requests per oracle

core function set
- add(componentNftId, objectNftId)
- activate(componentNftId, objectNftId)
- deactivate(componentNftId, objectNftId)
- objects(componentNftId) number of objects (all objects)
- getObject(coponentNftId, idx) returns (NftId)
- activeObjects(componentNftId) number of objects (all objects)
- getActiveObject(coponentNftId, idx) returns (NftId)
